path: /BodyLandmark
train: train/images

val: val/images

nc: 11

# class names
names: [
    "lung",
    "heart",
    "spine",
    "liver",
    "kidneys",
    "spleen",
    "stomach",
    "colon",
    "pancreas",
    "brain",
    "hip"
  ] 
